version: "3.8"

services:
  # backend api
  smart-brain-api:
    container_name: backend
    # image: node: 10.16.1
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      MYSQL_URI: mysql://root:12345678@mysql:3306/smartbrain-docker
    links:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api

  # mysql
  mysql:
    # container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: smartbrain-docker
      MYSQL_HOST: mysql
